### ISSUE TITLE
shouldRequestVideos always truthy

### ISSUE THREAD

**Issue by tomhooijenga** [autheos/autheos-embedcode#2]
```javascript
shouldRequestVideos() {
    if (!localStorage.getItem('autheos-ab')) {
       localStorage.setItem('autheos-ab', Math.random() < 0.5);
    }

    return localStorage.getItem('autheos-ab');
}
```
Because localStorage can only store strings, the key `autheos-ab` is "true" or "false". This on itself is not a problem, but I think you might have missed something on [this line](https://github.com/autheos/autheos-embedcode/blob/master/src/Autheos.js#L19):  ` if (this.abTestingEnabled && !this.shouldRequestVideos()) {`

```javascript
!"false" === false
!"true" === false
```

**Comment by Deltanic** [comment]
That was indeed an oversight, thanks for pointing it out. Fixed in b3158c0.
