### ISSUE TITLE
Autheos crashing site

### ISSUE THREAD

**Issue by tomhooijenga** [autheos/autheos-embedcode#3]
![unnamed](https://cloud.githubusercontent.com/assets/1853235/21010449/61309cc6-bd4c-11e6-8a3f-f83294768143.png)

Autheos' ab-testing is causing an error, also crashing the site. `return Promise().resolve([]);` should be             `return Promise.resolve([]);` (Notice the parenthesis. [located here](https://github.com/autheos/autheos-embedcode/blob/b3158c0988aad1610c8cad77298f23eda5623b53/src/Autheos.js#L21))

**Comment by Deltanic** [comment]
Thanks for spotting this problem, that's indeed a nasty issue. Resolved in 85ca713866f74e6d63beaa79b0a942bc56c5e96c.
